sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jfrench7919/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jfrench7919/docker-react npm run test -- --coverage
